blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/zainfathoni/kawalmasjid/discussions/category_choices
    about: Ask questions and discuss with the community
  - name: Visit the site
    url: https://kawalmasj.id
    about: Check out the examples
